### PR TITLE
Update composer.json

### LINKED ISSUE #69: support spatie/laravel-translatable v6
pump the package to support `spatie/laravel-translatable` `v6`

### PR DESCRIPTION
**Pull request by Saifallak**
fixes #69 allow spatie v6

### CODE REVIEW

**Comment by Tarpsvo** [comment]
Hi! Thanks for pointing this out. I kept version 5 support as well and released in version 1.12.0.

**Comment by Saifallak** [comment]
Ops, i thought `||` means from to ..
Because i see others use only one `|` for OR

**Comment by Saifallak** [comment]
Just a note, update readme as well to point v6

**Comment by Tarpsvo** [comment]
Thanks for the tip, updated README as well. :)

**Pull request closed without merging**
