### PR TITLE
Fix issue with Textarea field

### PR DESCRIPTION
**Pull request by milewski**

### CODE REVIEW

**Comment by Tarpsvo** [comment]
That's weird. I'm not able to reproduce this - does your model use `spatie/laravel-translatable`?

**Comment by milewski** [comment]
I don't have `laravel-translatable` installed explicitly? perhaps this package requires it? I didn't check but it works with everything else except TextareaField..  my nova version is `3.4.1` and my TextareaField contains this:

image

**Comment by milewski** [comment]
Besides this issue only happens in `detail` view. index/form works fine

**Comment by Tarpsvo** [comment]
Hmm, theoretically this package would require `spatie/laravel-translatable` (it's also the first step in the how to use guide in the README), but it does indeed work without it to some extent, due to a lot of failsafes added. Might as well go all in I guess and make it work without it. I'm debating on just wrapping the resolveForDisplay call in a try {} catch {} to be honest.

**Comment by milewski** [comment]
Well, I tried to add the `HasTranslations` see if it would make any difference in my use case.. but I realized that it requires the property to exist indeed on the model... Im using a "fake" model and saving all attributes into a single JSON column so the spatie/translatable package complains all properties need to be set etc...

**Comment by Tarpsvo** [comment]
Tried adding try {} catch {}, but it didn't catch it for some reason. Your solution seems good, thanks! Will release in a second.

**Pull request merged**
